metricbeat.config.modules:
  enabled: true
  reload.enabled: false
  reload.period: 10s
  path: ${path.config}/modules.d/*.yml

setup.dashboards.enabled: true
setup.kibana.host: https://search-plav-es-4omwj46r5h64gpx57a4ior3gtu.ap-northeast-2.es.amazonaws.com/_plugin/kibana

output.elasticsearch:
  hosts: ['https://search-plav-es-4omwj46r5h64gpx57a4ior3gtu.ap-northeast-2.es.amazonaws.com']
#  username: "metricbeat_writer"
#  password: "YOUR_PASSWORD"

metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true
#    xpack.monitoring.enabled: true
#    xpack.monitoring.collection.enabled: true
    xpack.monitoring.exporters.my_local:
      type: local
      use_ingest: false
    period: 10s
    hosts: [ 'https://search-plav-es-4omwj46r5h64gpx57a4ior3gtu.ap-northeast-2.es.amazonaws.com' ]
    deploy:
      resources:
        limits:
          cpus: '0.5'

monitoring:
  enabled: true
#  elasticsearch:
#    username: "metricbeat_writer"
#    password: "YOUR_PASSWORD"
