server.name: kibana
server.port: 5601
server.host: "0.0.0.0"

elasticsearch.hosts: [ "https://search-plav-es-4omwj46r5h64gpx57a4ior3gtu.ap-northeast-2.es.amazonaws.com" ]

monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: elastic
elasticsearch.password: changeme
xpack.security.encryptionKey: "elasticsearch_security_key__char"
xpack.security.sessionTimeout: 600000